[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  framework = "#static"
  port = 8888
  publish = "."
  functions = "netlify/functions"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions.chat]
  timeout = 30
